name: Sync

on:
  schedule:
    - cron: '57/30 * * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    permissions:
      contents: 'write'
      id-token: 'write'

    env:
      BUCKET_NAME: linux-mirror-db

    steps:
      - uses: actions/checkout@v2
        with:
          ref: main

      - name: Update mirror
        run: |
          git config --global user.name gha
          git config --global user.email actions@github.com
          git remote add upstream https://github.com/aquasecurity/vuln-list.git
          git fetch upstream
          git merge --allow-unrelated-histories -Xtheirs upstream/main
          git push
      - name: Obtain Ubuntu CVEs
        run: |
          jq '.|select(.Patches.linux)|{cve:.Candidate,references:.References,commits:(.References|map(capture("(?<commit>\b[0-9a-f]{40}\b)")|.commit)|unique_by(.))}' ubuntu/*/CVE-* | jq -s . > ubuntu_kernel.json
      - name: Obtain RedHat CVEs
        run: |
          wget https://github.com/aquasecurity/vuln-list-redhat/archive/refs/heads/main.zip
          unzip main.zip
          rm main.zip
          jq '(.|select(.package_state[].package_name=="kernel")|{cve:.name,references:(.references|map(.|split("\n"))),commits:(.references|map(capture("(?<commit>[0-9a-f]{40})";"gi")|.commit))})' vuln-list-redhat-main/*/CVE-* 2>/dev/null | jq -s . > redhat_kernel.json
      - name: Obtain NVD CVEs
        run: |
          wget https://github.com/aquasecurity/vuln-list-nvd/archive/refs/heads/main.zip
          unzip main.zip
          rm main.zip
          jq '{cve:.id,references:(.references|map(.url))}|.commits=(.references|map(capture("(?<commit>[0-9a-f]{40})").commit))' $(grep -ril kernel vuln-list-nvd-main/api) | jq -s . >> nvd_kernel.json
      - name: Obtain nluedtke CVEs
        run: |
          wget https://github.com/nluedtke/linux_kernel_cves/raw/master/data/CVEs.txt
          jq --slurp --raw-input '.|split("\n")|map(split(": ")|{cve:.[0],commits:(.[1]|select(.)|split(" - ")|(.[1]|select(.)|split(" "))[0:1]|select(.[0]|test("[0-9a-f]{40}")))})' CVEs.txt > nluedtke_kernel.json
      - name: Obtain kernelCTF CVEs
        run: |
          curl -L 'https://docs.google.com/spreadsheets/d/e/2PACX-1vS1REdTA29OJftst8xN5B5x8iIUcxuK6bXdzF8G1UXCmRtoNsoQ9MbebdRdFnj6qZ0Yd7LwQfvYC2oF/pub?gid=2095368189&single=true&output=tsv' | jq --slurp --raw-input '. | split("\n") | map(split("\t")|(.[6] | scan("[0-9a-f]{40,}")) as $commit | .[8] | scan("CVE-[0-9]+-[0-9]+") | ({cve:., commits: [$commit]})) | unique_by(.)' > kernelctf_kernel.json
      - name: Merge CVEs
        run: |
          jq -r '.[]|.cve as $cve|.commits[]|[$cve, .]' *_kernel.json | jq -sr '([["cve","commit"]]+unique_by(.))|.[]|@csv' > cve.csv
      - uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: 'projects/799795028847/locations/global/workloadIdentityPools/github-pool/providers/github-provider-new'
          service_account: 'github@sdcpocs.iam.gserviceaccount.com'

      - uses: 'google-github-actions/upload-cloud-storage@v0'
        with:
          destination: '${{ env.BUCKET_NAME }}/'
          path: ./cve.csv
          headers: |-
            cache-control: no-cache
